# Generated by Django 5.2.3 on 2025-07-03 02:33

import MariaAlvezApp.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelatoriosGerais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Relatório Geral',
                'verbose_name_plural': 'Relatórios Gerais',
                'permissions': [('can_view_reports', 'Can view general reports')],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Nome', max_length=150, verbose_name='Nome')),
                ('especie', models.CharField(default='Especie', max_length=100, verbose_name='Espécie')),
                ('idade_anos', models.PositiveIntegerField(default=0, verbose_name='Anos')),
                ('idade_meses', models.PositiveIntegerField(default=0, verbose_name='Meses')),
                ('idade_dias', models.PositiveIntegerField(default=0, verbose_name='Dias')),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], default='Sexo', max_length=15, verbose_name='Sexo')),
                ('peso', models.DecimalField(decimal_places=3, default=0, help_text='Peso em quilogramas', max_digits=10, verbose_name='Peso (kg)')),
                ('castrado', models.BooleanField(default=False, verbose_name='Castrado(a)')),
                ('rfid', models.CharField(blank=True, default='0', max_length=128, null=True, unique=True, verbose_name='RFID')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
            },
        ),
        migrations.CreateModel(
            name='EstoqueMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=255, unique=True, verbose_name='Medicamento')),
                ('tipo_medicamento', models.CharField(choices=[('vacina', 'Vacina'), ('vermifugo', 'Vermífugo'), ('medicamento', 'Medicamento')], default='medicamento', help_text='Classifique o tipo do medicamento', max_length=20, verbose_name='Tipo de Medicamento')),
                ('lote', models.CharField(max_length=100, unique=True, verbose_name='Lote')),
                ('data_validade', models.DateField(verbose_name='Data de Validade')),
                ('quantidade', models.PositiveIntegerField(default=0, editable=False, verbose_name='Quantidade em Estoque')),
                ('data_cadastro', models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Data de Entrada')),
            ],
            options={
                'verbose_name': 'Lote de Medicamento',
                'verbose_name_plural': 'Estoque de Medicamentos',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[MariaAlvezApp.models.validar_cpf], verbose_name='CPF')),
                ('telefone', models.CharField(max_length=15, validators=[MariaAlvezApp.models.validar_telefone], verbose_name='Telefone')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Tutor',
                'verbose_name_plural': 'Tutores',
            },
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Nome do Veterinário', max_length=255, verbose_name='Nome do Veterinário')),
                ('crmv', models.CharField(default='00000-UF', max_length=50, unique=True, verbose_name='CRMV')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Veterinário',
                'verbose_name_plural': 'Veterinários',
            },
        ),
        migrations.CreateModel(
            name='AgendamentoConsultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data da Consulta')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_consultas', to='MariaAlvezApp.animal', verbose_name='Animal')),
            ],
            options={
                'verbose_name': 'Agendamento de Consulta',
                'verbose_name_plural': 'Agendamentos de Consultas',
            },
        ),
        migrations.CreateModel(
            name='ConsultaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atendimento', models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora da consulta')),
                ('tipo_atendimento', models.CharField(blank=True, help_text='Tipo de atendimento (ex: Rotina, Emergência)', max_length=100, null=True)),
                ('diagnostico', models.TextField(blank=True, help_text='Diagnóstico da consulta', null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais da consulta', null=True)),
                ('frequencia_cardiaca', models.IntegerField(blank=True, help_text='Frequência cardíaca em batimentos por minuto (BPM)', null=True)),
                ('frequencia_respiratoria', models.IntegerField(blank=True, help_text='Frequência respiratoria em respirações por minuto (RPM)', null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, help_text='Temperatura corporal em graus Celsius (°C)', max_digits=4, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Peso do animal em quilogramas (Kg) ', max_digits=5, null=True)),
                ('avaliacao_mucosa', models.CharField(blank=True, help_text='Avaliação da mucosa (ex: Rósea, Pálida, Ictérica)', max_length=100, null=True)),
                ('tempo_preenchimento_capilar', models.CharField(blank=True, help_text='Tempo de preenchimento capilar (ex: < 2 segundos, 3 segundos)', max_length=50, null=True)),
                ('agendamento_origem', models.OneToOneField(blank=True, help_text='Agendamento que originou esta consulta (se houver).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consulta_gerada', to='MariaAlvezApp.agendamentoconsultas', verbose_name='Agendamento de Origem')),
                ('animal', models.ForeignKey(blank=True, help_text='Selecione o animal atendido na consulta', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historico_consultas', to='MariaAlvezApp.animal', verbose_name='Animal Atendido')),
            ],
            options={
                'verbose_name': 'Consulta Clínica',
                'verbose_name_plural': 'Consultas Clínicas',
                'ordering': ['-data_atendimento'],
            },
        ),
        migrations.CreateModel(
            name='Exames',
            fields=[
                ('id_exame', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Exame')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Exame')),
                ('tipo', models.CharField(blank=True, choices=[('Imagem', 'Imagem'), ('Laboratorial', 'Laboratorial'), ('Clínico', 'Clínico')], max_length=50, null=True, verbose_name='Tipo de Exame')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='exames/', verbose_name='Anexo do Exame')),
                ('data_exame', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Realização do Exame')),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MariaAlvezApp.animal', verbose_name='Animal')),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exames', to='MariaAlvezApp.consultaclinica', verbose_name='Consulta Associada')),
            ],
            options={
                'verbose_name': 'Exame',
                'verbose_name_plural': 'Exames',
                'ordering': ['-data_exame', 'animal__nome'],
            },
        ),
        migrations.CreateModel(
            name='MedicamentoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_aplicada', models.PositiveIntegerField(verbose_name='Quantidade Aplicada')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MariaAlvezApp.consultaclinica', verbose_name='Consulta Clínica')),
                ('medicamento_estoque', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MariaAlvezApp.estoquemedicamento', verbose_name='Medicamento (Lote)')),
            ],
            options={
                'verbose_name': 'Medicamento na Consulta',
                'verbose_name_plural': 'Medicamentos na Consulta',
            },
        ),
        migrations.AddField(
            model_name='consultaclinica',
            name='medicamentos_aplicados',
            field=models.ManyToManyField(blank=True, related_name='consultas_onde_aplicado', through='MariaAlvezApp.MedicamentoConsulta', to='MariaAlvezApp.estoquemedicamento', verbose_name='Medicamentos Aplicados na Consulta'),
        ),
        migrations.CreateModel(
            name='MovimentoEstoqueMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10, verbose_name='Tipo de Movimento')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade Movimentada')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data do Movimento')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('estoque_item', models.ForeignKey(blank=True, help_text='Selecione o lote de medicamento ao qual o movimento se refere.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='MariaAlvezApp.estoquemedicamento', verbose_name='Lote de Medicamento')),
            ],
            options={
                'verbose_name': 'Movimento de Estoque',
                'verbose_name_plural': 'Movimentos de Estoque',
            },
        ),
        migrations.CreateModel(
            name='RegistroVacinacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aplicacao', models.DateField(blank=True, null=True, verbose_name='Data de Aplicação')),
                ('data_revacinacao', models.DateField(blank=True, null=True, verbose_name='Data Revacinação')),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MariaAlvezApp.animal', verbose_name='Animal')),
                ('medicamento_aplicado', models.ForeignKey(blank=True, limit_choices_to={'tipo_medicamento': 'vacina'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MariaAlvezApp.estoquemedicamento', verbose_name='Medicamento/Lote Aplicado')),
            ],
            options={
                'verbose_name': 'Registro de Vacinação',
                'verbose_name_plural': 'Registros de Vacinação',
            },
        ),
        migrations.CreateModel(
            name='RegistroVermifugos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_administracao', models.DateField(blank=True, null=True, verbose_name='Data de Administração')),
                ('data_readministracao', models.DateField(blank=True, null=True, verbose_name='Data Readministração')),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MariaAlvezApp.animal', verbose_name='Animal')),
                ('medicamento_administrado', models.ForeignKey(blank=True, limit_choices_to={'tipo_medicamento': 'vermifugo'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MariaAlvezApp.estoquemedicamento', verbose_name='Vermífugo/Lote Administrado')),
            ],
            options={
                'verbose_name': 'Registro de Vermífugo',
                'verbose_name_plural': 'Registros de Vermífugos',
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='tutor',
            field=models.ForeignKey(help_text='Selecione o tutor responsável por este animal.', on_delete=django.db.models.deletion.CASCADE, related_name='animais_tutor', to='MariaAlvezApp.tutor', verbose_name='Tutor do Animal'),
        ),
        migrations.AddField(
            model_name='consultaclinica',
            name='veterinario',
            field=models.ForeignKey(blank=True, help_text='Selecione o veterinário responsável pela consulta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_realizadas', to='MariaAlvezApp.veterinario', verbose_name='Veterinário Responsável'),
        ),
        migrations.AddIndex(
            model_name='agendamentoconsultas',
            index=models.Index(fields=['data_consulta'], name='MariaAlvezA_data_co_02161e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='medicamentoconsulta',
            unique_together={('consulta', 'medicamento_estoque')},
        ),
    ]
