# Generated by Django 5.2.3 on 2025-06-22 20:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatoriosGerais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Relatório Geral',
                'verbose_name_plural': 'Relatórios GeraiS',
                'permissions': [('can_view_reports', 'Can view general reports')],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='consultaclinica',
            options={'ordering': ['-data_atendimento'], 'verbose_name': 'Consulta Clínica', 'verbose_name_plural': 'Consultas Clínicas'},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'verbose_name': 'Tutor', 'verbose_name_plural': 'Tutores'},
        ),
        migrations.AddField(
            model_name='consultaclinica',
            name='avaliacao_mucosa',
            field=models.CharField(blank=True, help_text='Avaliação da mucosa (ex: Rósea, Pálida, Ictérica)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consultaclinica',
            name='data_atendimento',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora da consulta'),
        ),
        migrations.AddField(
            model_name='consultaclinica',
            name='diagnostico',
            field=models.TextField(blank=True, help_text='Diagnóstico da consulta', null=True),
        ),
        migrations.AddField(
            model_name='consultaclinica',
            name='exames_realizados',
            field=models.TextField(blank=True, help_text='Nomes ou IDs dos exames realizados (separados por vírgula)', null=True),
        ),
        migrations.AddField(
            model_name='consultaclinica',
            name='frequencia_cardiaca',
            field=models.IntegerField(blank=True, help_text='Frequência cardíaca em batimentos por minuto (BPM)', null=True),
        ),
        migrations.AddField(
            model_name='consultaclinica',
            name='frequencia_respiratoria',
            field=models.IntegerField(blank=True, help_text='Frequência respiratória em respirações por minuto (RPM)', null=True),
        ),
        migrations.AddField(
            model_name='consultaclinica',
            name='nome_animal',
            field=models.CharField(blank=True, help_text='Nome do animal atendido', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consultaclinica',
            name='nome_vet_responsavel',
            field=models.CharField(blank=True, help_text='Nome do veterinário responsável', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consultaclinica',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações adicionais da consulta', null=True),
        ),
        migrations.AddField(
            model_name='consultaclinica',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso do animal em quilogramas (Kg)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='consultaclinica',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Temperatura corporal em graus Celsius (°C)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='consultaclinica',
            name='tempo_preenchimento_capilar',
            field=models.CharField(blank=True, help_text='Tempo de preenchimento capilar (ex: < 2 segundos, 3 segundos)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consultaclinica',
            name='tipo_atendimento',
            field=models.CharField(blank=True, help_text='Tipo de atendimento (ex: Rotina, Emergência)', max_length=100, null=True),
        ),
    ]
