# Generated by Django 5.2.4 on 2025-07-03 22:42

import MariaAlvezApp.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentoconsultas',
            name='is_castracao',
            field=models.BooleanField(default=False, help_text='Marque se este agendamento for para um procedimento de castração.', verbose_name='Agendamento para Castração?'),
        ),
        migrations.AlterField(
            model_name='agendamentoconsultas',
            name='animal',
            field=models.ForeignKey(help_text='Selecione o Animal para agendamento!', on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_consultas', to='MariaAlvezApp.animal', verbose_name='Animal'),
        ),
        migrations.AlterField(
            model_name='agendamentoconsultas',
            name='data_consulta',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Escolha a data da consulta!', null=True, verbose_name='Data da Consulta'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='castrado',
            field=models.BooleanField(default=False, help_text='Marque se o animal for castrado', verbose_name='Castrado(a)'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.CharField(default='Especie', help_text='Espécie do Animal. Ex:(Cachorro, Gato, Passaro, etc)', max_length=100, verbose_name='Espécie'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='idade_anos',
            field=models.PositiveIntegerField(help_text='Quantos anos o animal tem', verbose_name='Anos'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='idade_dias',
            field=models.PositiveIntegerField(help_text='Quantos dias o animal tem', verbose_name='Dias'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='idade_meses',
            field=models.PositiveIntegerField(help_text='Quantos meses o animal tem', verbose_name='Meses'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='nome',
            field=models.CharField(default='Nome', help_text='Nome do Animal', max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='rfid',
            field=models.CharField(blank=True, default='0', help_text='RFID segue padrão ISO 11784/11785 EXEMPLOS: 985 112003456789', max_length=128, null=True, unique=True, verbose_name='RFID'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], default='Sexo', help_text='Escolha o sexo do animal', max_length=15, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='movimentoestoquemedicamento',
            name='data',
            field=models.DateTimeField(auto_now_add=True, help_text='Data de Hoje', verbose_name='Data do Movimento'),
        ),
        migrations.AlterField(
            model_name='movimentoestoquemedicamento',
            name='estoque_item',
            field=models.ForeignKey(blank=True, help_text='Selecione o medicamento ao qual o movimento se refere.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='MariaAlvezApp.estoquemedicamento', verbose_name='Lote de Medicamento'),
        ),
        migrations.AlterField(
            model_name='movimentoestoquemedicamento',
            name='quantidade',
            field=models.PositiveIntegerField(help_text='Escolha a quantidade movimentada', verbose_name='Quantidade Movimentada'),
        ),
        migrations.AlterField(
            model_name='movimentoestoquemedicamento',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], help_text='Escolha o tipo de movimento: ENTRADA ou SAIDA', max_length=10, verbose_name='Tipo de Movimento'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='cep',
            field=models.CharField(help_text='Clique para buscar o CEP preenchido.', max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='cidade',
            field=models.CharField(help_text='Cidade do Tutor', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='cpf',
            field=models.CharField(help_text='CPF do Tutor', max_length=14, unique=True, validators=[MariaAlvezApp.models.validar_cpf], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='data_nascimento',
            field=models.DateField(help_text='Data de Nascimento do Tutor. Ex: 19/09/2000', verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='endereco',
            field=models.CharField(help_text='Lembre de Preencher com o numero da casa. Ex:(Rua Exemplo, 999)', max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='estado',
            field=models.CharField(help_text='Estado do Tutor', max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='nome',
            field=models.CharField(help_text='Nome Completo do tutor!', max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='telefone',
            field=models.CharField(help_text='Telefone do tutor com DDD. Ex:(49998086201)', max_length=15, validators=[MariaAlvezApp.models.validar_telefone], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='crmv',
            field=models.CharField(help_text='CRMV do Veterinario Ex: (65485-SC)', max_length=50, unique=True, verbose_name='CRMV'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='email',
            field=models.EmailField(blank=True, help_text='Email do veterinario', max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='nome',
            field=models.CharField(help_text='Nome Completo do veterinario', max_length=255, verbose_name='Nome do Veterinário'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='telefone',
            field=models.CharField(help_text='Telefone Veterinario', max_length=15, verbose_name='Telefone'),
        ),
    ]
