# Generated by Django 5.2.2 on 2025-06-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroVermifugos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Registro de Vermífugo',
                'verbose_name_plural': 'Registros de Vermífugos',
            },
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Veterinário',
                'verbose_name_plural': 'Veterinários',
            },
        ),
        migrations.RenameModel(
            old_name='ProcedimentoCirurgico',
            new_name='AgendamentoConsultas',
        ),
        migrations.RenameModel(
            old_name='Paciente',
            new_name='Animal',
        ),
        migrations.RenameModel(
            old_name='Prescricao',
            new_name='ConsultaClinica',
        ),
        migrations.RenameModel(
            old_name='RegistroVacina',
            new_name='RegistroVacinacao',
        ),
        migrations.DeleteModel(
            name='Agendamento',
        ),
        migrations.AlterModelOptions(
            name='agendamentoconsultas',
            options={'verbose_name': 'Agendamento de Consulta', 'verbose_name_plural': 'Agendamentos de Consultas'},
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Animal', 'verbose_name_plural': 'Animais'},
        ),
        migrations.AlterModelOptions(
            name='consultaclinica',
            options={'verbose_name': 'Consulta Clínica', 'verbose_name_plural': 'Consultas Clínicas'},
        ),
        migrations.AlterModelOptions(
            name='registrovacinacao',
            options={'verbose_name': 'Registro de Vacinacão', 'verbose_name_plural': 'Registros de Vacinações'},
        ),
    ]
