# Generated by Django 5.2.3 on 2025-06-22 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultaclinica',
            name='tutor',
        ),
        migrations.AddField(
            model_name='registrovacinacao',
            name='consulta_clinica',
            field=models.ForeignKey(blank=True, help_text='Consulta clínica onde esta vacinação foi realizada ou registrada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacinacoes_realizadas', to='MariaAlvezApp.consultaclinica', verbose_name='Consulta Clínica Associada'),
        ),
        migrations.AddField(
            model_name='registrovermifugos',
            name='consulta_clinica',
            field=models.ForeignKey(blank=True, help_text='Consulta clínica onde esta vermifugação foi realizada ou registrada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vermifugacoes_realizadas', to='MariaAlvezApp.consultaclinica', verbose_name='Consulta Clínica Associada'),
        ),
        migrations.CreateModel(
            name='MedicamentoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_aplicada', models.PositiveIntegerField(verbose_name='Quantidade Aplicada')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MariaAlvezApp.consultaclinica', verbose_name='Consulta Clínica')),
                ('medicamento_estoque', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MariaAlvezApp.estoquemedicamento', verbose_name='Medicamento (Lote)')),
            ],
            options={
                'verbose_name': 'Medicamento na Consulta',
                'verbose_name_plural': 'Medicamentos na Consulta',
                'unique_together': {('consulta', 'medicamento_estoque')},
            },
        ),
        migrations.AddField(
            model_name='consultaclinica',
            name='medicamentos_aplicados',
            field=models.ManyToManyField(blank=True, related_name='consultas_onde_aplicado', through='MariaAlvezApp.MedicamentoConsulta', to='MariaAlvezApp.estoquemedicamento', verbose_name='Medicamentos Aplicados na Consulta'),
        ),
    ]
