# Generated by Django 5.2.3 on 2025-06-22 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0002_relatoriosgerais_alter_consultaclinica_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatoriosgerais',
            options={'managed': False, 'permissions': [('can_view_reports', 'Can view general reports')], 'verbose_name': 'Relatório Geral', 'verbose_name_plural': 'Relatórios Gerais'},
        ),
    ]
