# Generated by Django 5.2.3 on 2025-06-23 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0002_remove_consultaclinica_tutor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrovacinacao',
            name='consulta_clinica',
        ),
        migrations.RemoveField(
            model_name='registrovermifugos',
            name='consulta_clinica',
        ),
    ]
