# Generated by Django 5.2.3 on 2025-07-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0002_alter_agendamentoconsultas_animal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentoconsultas',
            name='is_castracao',
            field=models.BooleanField(default=False, help_text='Marque se este agendamento for para um procedimento de castração.', verbose_name='Agendamento para Castração?'),
        ),
    ]
