# Generated by Django 5.2.3 on 2025-06-13 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0002_registrovermifugos_veterinario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrovacinacao',
            options={'verbose_name': 'Registro de Vacinação', 'verbose_name_plural': 'Registros de Vacinações'},
        ),
        migrations.AddField(
            model_name='agendamentoconsultas',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MariaAlvezApp.animal'),
        ),
        migrations.AddField(
            model_name='agendamentoconsultas',
            name='data_consulta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamentoconsultas',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MariaAlvezApp.tutor'),
        ),
        migrations.AddField(
            model_name='animal',
            name='castrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animal',
            name='especie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='idade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='rfid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='sexo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MariaAlvezApp.tutor'),
        ),
        migrations.AddField(
            model_name='consultaclinica',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MariaAlvezApp.animal'),
        ),
        migrations.AddField(
            model_name='consultaclinica',
            name='avaliacao_mucosa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consultaclinica',
            name='data_atendimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultaclinica',
            name='diagnostico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultaclinica',
            name='exame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MariaAlvezApp.exames'),
        ),
        migrations.AddField(
            model_name='consultaclinica',
            name='frequencia_cardiaca',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultaclinica',
            name='frequencia_respiratoria',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultaclinica',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultaclinica',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='consultaclinica',
            name='tcp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consultaclinica',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='consultaclinica',
            name='tipo_atendimento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consultaclinica',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MariaAlvezApp.tutor'),
        ),
        migrations.AddField(
            model_name='consultaclinica',
            name='vet_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MariaAlvezApp.veterinario'),
        ),
        migrations.AddField(
            model_name='exames',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='exames/'),
        ),
        migrations.AddField(
            model_name='exames',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exames',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exames',
            name='tipo_exame',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicamentos',
            name='data_da_entrada',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='medicamentos',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicamentos',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicamentos',
            name='validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrovacinacao',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MariaAlvezApp.animal'),
        ),
        migrations.AddField(
            model_name='registrovacinacao',
            name='data_aplicacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrovacinacao',
            name='data_revacinacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrovacinacao',
            name='medicamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MariaAlvezApp.medicamentos'),
        ),
        migrations.AddField(
            model_name='registrovermifugos',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MariaAlvezApp.animal'),
        ),
        migrations.AddField(
            model_name='registrovermifugos',
            name='data_administracao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrovermifugos',
            name='data_readministracao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrovermifugos',
            name='medicamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MariaAlvezApp.medicamentos'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='cidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='veterinario',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='veterinario',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
