# Generated by Django 5.2.4 on 2025-07-03 03:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0002_alter_agendamentoconsultas_animal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentoconsultas',
            name='data_consulta',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Escolha a data da consulta!', null=True, verbose_name='Data da Consulta'),
        ),
    ]
