# Generated by Django 5.2.3 on 2025-06-12 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0002_registrovermifugos_veterinario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrovacinacao',
            options={'verbose_name': 'Registro de Vacinação', 'verbose_name_plural': 'Registros de Vacinação'},
        ),
        migrations.AddField(
            model_name='registrovacinacao',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MariaAlvezApp.animal'),
        ),
        migrations.AddField(
            model_name='registrovacinacao',
            name='data_aplicacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrovacinacao',
            name='data_revacinacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Revavinação'),
        ),
        migrations.AddField(
            model_name='registrovacinacao',
            name='medicamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MariaAlvezApp.medicamentos'),
        ),
    ]
