# Generated by Django 5.2.4 on 2025-07-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0002_agendamentoconsultas_is_castracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='data_nascimento',
            field=models.DateField(blank=True, help_text='Data de nascimento exata do animal. Se vazia, será calculada com base na idade fornecida.', null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='idade_anos',
            field=models.PositiveIntegerField(default=0, help_text='Quantos anos o animal tem (será preenchido automaticamente pela data de nascimento)', verbose_name='Anos'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='idade_dias',
            field=models.PositiveIntegerField(default=0, help_text='Quantos dias o animal tem (será preenchido automaticamente pela data de nascimento)', verbose_name='Dias'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='idade_meses',
            field=models.PositiveIntegerField(default=0, help_text='Quantos meses o animal tem (será preenchido automaticamente pela data de nascimento)', verbose_name='Meses'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='rfid',
            field=models.CharField(blank=True, default='', help_text='RFID segue padrão ISO 11784/11785 EXEMPLOS: 985 112003456789', max_length=128, null=True, unique=True, verbose_name='RFID'),
        ),
    ]
