# Generated by Django 5.2.3 on 2025-06-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0002_registrovermifugos_veterinario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='castrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animal',
            name='especie',
            field=models.CharField(default='Especie', max_length=100),
        ),
        migrations.AddField(
            model_name='animal',
            name='idade_anos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='animal',
            name='idade_dias',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='animal',
            name='idade_meses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='animal',
            name='nome',
            field=models.CharField(default='Nome', max_length=150),
        ),
        migrations.AddField(
            model_name='animal',
            name='peso_unidade',
            field=models.CharField(choices=[('kg', 'Quilos'), ('g', 'Gramas')], default='Unidade', max_length=10),
        ),
        migrations.AddField(
            model_name='animal',
            name='peso_valor',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='animal',
            name='rfid',
            field=models.CharField(default=0, max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], default='Sexo', max_length=15),
        ),
    ]
