# Generated by Django 5.2.3 on 2025-06-12 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0002_registrovermifugos_veterinario_and_more'),
    ]

    operations = [
    ]
