# Generated by Django 5.2.3 on 2025-06-23 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0003_remove_registrovacinacao_consulta_clinica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentoestoquemedicamento',
            name='data_validade',
        ),
        migrations.RemoveField(
            model_name='movimentoestoquemedicamento',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='movimentoestoquemedicamento',
            name='medicamento',
        ),
        migrations.AddField(
            model_name='movimentoestoquemedicamento',
            name='estoque_item',
            field=models.ForeignKey(blank=True, help_text='Selecione o lote de medicamento ao qual o movimento se refere.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='MariaAlvezApp.estoquemedicamento', verbose_name='Lote de Medicamento'),
        ),
        migrations.AlterField(
            model_name='consultaclinica',
            name='frequencia_respiratoria',
            field=models.IntegerField(blank=True, help_text='Frequência respiratoria em respirações por minuto (RPM)', null=True),
        ),
    ]
