# Generated by Django 5.2.3 on 2025-06-12 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0003_alter_registrovacinacao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrovermifugos',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MariaAlvezApp.animal'),
        ),
        migrations.AddField(
            model_name='registrovermifugos',
            name='data_administracao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrovermifugos',
            name='data_readiministracao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Readiministração'),
        ),
        migrations.AddField(
            model_name='registrovermifugos',
            name='medicamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MariaAlvezApp.medicamentos'),
        ),
        migrations.AlterField(
            model_name='registrovacinacao',
            name='data_revacinacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Revacinação'),
        ),
    ]
