# Generated by Django 5.2.4 on 2025-07-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0003_animal_data_nascimento_alter_animal_idade_anos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultaclinica',
            name='tipo_atendimento',
            field=models.CharField(choices=[('CONSULTA_ROTINA', 'Consulta de Rotina'), ('EMERGENCIA', 'Emergência'), ('OUTRO', 'Outro')], default='CONSULTA_ROTINA', help_text='Selecione o tipo de atendimento realizado.', max_length=50, verbose_name='Tipo de Atendimento'),
        ),
    ]
