# Generated by Django 5.2.2 on 2025-06-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0003_alter_tutor_options_tutor_cep_tutor_cidade_tutor_cpf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='sobrenome',
        ),
        migrations.AlterField(
            model_name='tutor',
            name='endereco',
            field=models.CharField(max_length=200),
        ),
    ]
