# Generated by Django 5.2.3 on 2025-06-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0003_auto_20250612_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinario',
            name='crmv',
            field=models.CharField(default=10, help_text='Número de registro no Conselho Regional de Medicina Veterinária.', max_length=20, unique=True, verbose_name='CRMV'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veterinario',
            name='nome',
            field=models.CharField(default=10, max_length=100, verbose_name='Nome Completo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veterinario',
            name='telefone',
            field=models.CharField(default=10, help_text='Ex: (49) 99999-8888', max_length=20, verbose_name='Telefone'),
            preserve_default=False,
        ),
    ]
