# Generated by Django 5.2.3 on 2025-06-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0003_animal_castrado_animal_especie_animal_idade_anos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='peso_unidade',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='peso_valor',
        ),
        migrations.AddField(
            model_name='animal',
            name='peso',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Peso em quilogramas (kg)', max_digits=10),
        ),
    ]
