# Generated by Django 5.2.3 on 2025-06-23 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0004_remove_movimentoestoquemedicamento_data_validade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exames',
            options={'ordering': ['-data_exame', 'animal__nome'], 'verbose_name': 'Exame', 'verbose_name_plural': 'Exames'},
        ),
        migrations.RemoveField(
            model_name='consultaclinica',
            name='exames_realizados',
        ),
        migrations.AddField(
            model_name='exames',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exames', to='MariaAlvezApp.consultaclinica', verbose_name='Consulta Associada'),
        ),
        migrations.AlterField(
            model_name='exames',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MariaAlvezApp.animal', verbose_name='Animal'),
        ),
        migrations.AlterField(
            model_name='exames',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Exame'),
        ),
    ]
