# Generated by Django 5.2.3 on 2025-06-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0004_remove_animal_peso_unidade_remove_animal_peso_valor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='peso',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
