# Generated by Django 5.2.3 on 2025-06-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0004_registrovermifugos_animal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrovermifugos',
            name='data_readiministracao',
        ),
        migrations.AddField(
            model_name='registrovermifugos',
            name='data_readministracao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Readministração'),
        ),
    ]
