# Generated by Django 5.2.4 on 2025-07-04 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0004_alter_consultaclinica_tipo_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrovacinacao',
            name='animal',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='MariaAlvezApp.animal', verbose_name='Animal'),
        ),
        migrations.AlterField(
            model_name='registrovacinacao',
            name='data_aplicacao',
            field=models.DateField(blank=True, verbose_name='Data de Aplicação'),
        ),
        migrations.AlterField(
            model_name='registrovacinacao',
            name='data_revacinacao',
            field=models.DateField(blank=True, verbose_name='Data Revacinação'),
        ),
    ]
