# Generated by Django 5.2.4 on 2025-07-04 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0005_alter_registrovacinacao_animal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrovacinacao',
            name='animal',
            field=models.ForeignKey(help_text='Selecione o animal vacinado.', on_delete=django.db.models.deletion.CASCADE, to='MariaAlvezApp.animal', verbose_name='Animal'),
        ),
        migrations.AlterField(
            model_name='registrovacinacao',
            name='data_aplicacao',
            field=models.DateField(help_text='Informe a data em que a vacina foi aplicada.', verbose_name='Data de Aplicação'),
        ),
        migrations.AlterField(
            model_name='registrovacinacao',
            name='data_revacinacao',
            field=models.DateField(help_text='Informe a data da próxima revacinação.', verbose_name='Data Revacinação'),
        ),
        migrations.AlterField(
            model_name='registrovacinacao',
            name='medicamento_aplicado',
            field=models.ForeignKey(help_text='Selecione a vacina (lote) aplicada. Apenas vacinas serão listadas.', limit_choices_to={'tipo_medicamento': 'vacina'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MariaAlvezApp.estoquemedicamento', verbose_name='Vacina/Lote Aplicado'),
        ),
    ]
