# Generated by Django 5.2.3 on 2025-06-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0005_alter_exames_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PainelGerencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Painel Gerencial',
                'verbose_name_plural': 'Painel Gerencial',
                'managed': False,
            },
        ),
    ]
