# Generated by Django 5.2.3 on 2025-06-26 23:24

import MariaAlvezApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0005_alter_exames_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='cep',
            field=models.CharField(max_length=9, validators=[MariaAlvezApp.models.validar_cep], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='estado',
            field=models.CharField(max_length=2, validators=[MariaAlvezApp.models.validar_estado], verbose_name='Estado'),
        ),
    ]
