# Generated by Django 5.2.2 on 2025-06-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0005_alter_tutor_cpf_alter_tutor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='sobrenome',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutor',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
