# Generated by Django 5.2.4 on 2025-07-04 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0006_alter_registrovacinacao_animal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrovermifugos',
            name='animal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MariaAlvezApp.animal', verbose_name='Animal'),
        ),
        migrations.AlterField(
            model_name='registrovermifugos',
            name='data_administracao',
            field=models.DateField(null=True, verbose_name='Data de Administração'),
        ),
        migrations.AlterField(
            model_name='registrovermifugos',
            name='data_readministracao',
            field=models.DateField(null=True, verbose_name='Data Readministração'),
        ),
        migrations.AlterField(
            model_name='registrovermifugos',
            name='medicamento_administrado',
            field=models.ForeignKey(limit_choices_to={'tipo_medicamento': 'vermifugo'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MariaAlvezApp.estoquemedicamento', verbose_name='Vermífugo/Lote Administrado'),
        ),
    ]
