# Generated by Django 5.2.3 on 2025-06-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0006_alter_tutor_cep_alter_tutor_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='cep',
            field=models.CharField(max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='estado',
            field=models.CharField(max_length=2, verbose_name='Estado'),
        ),
    ]
