# Generated by Django 5.2.4 on 2025-07-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0007_alter_registrovermifugos_animal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultaclinica',
            name='diagnostico',
            field=models.TextField(blank=True, help_text='Diagnóstico da consulta', null=True, verbose_name='Diagnóstico'),
        ),
        migrations.AlterField(
            model_name='consultaclinica',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações adicionais da consulta', null=True, verbose_name='Observações'),
        ),
    ]
