# Generated by Django 5.2.2 on 2025-06-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0007_alter_tutor_nome_alter_tutor_sobrenome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='sobrenome',
        ),
        migrations.AddField(
            model_name='tutor',
            name='estado',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
