# Generated by Django 5.2.3 on 2025-06-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0007_alter_tutor_cep_alter_tutor_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='rfid',
            field=models.CharField(blank=True, default='0', max_length=128, null=True, unique=True, verbose_name='RFID'),
        ),
    ]
