# Generated by Django 5.2 on 2025-06-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0006_alter_animal_peso'),
        ('MariaAlvezApp', '0008_remove_tutor_email_remove_tutor_sobrenome_and_more'),
    ]

    operations = [
    ]
