# Generated by Django 5.2.3 on 2025-07-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0008_alter_animal_rfid'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoquemedicamento',
            name='tipo_medicamento',
            field=models.CharField(choices=[('vacina', 'Vacina'), ('vermifugo', 'Vermífugo'), ('medicamento', 'Medicamento')], default='medicamento', help_text='Classifique o tipo do medicamento', max_length=20, verbose_name='Tipo de Medicamento'),
        ),
    ]
