# Generated by Django 5.2 on 2025-06-15 17:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0009_merge_20250615_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentoconsultas',
            name='animal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_consultas', to='MariaAlvezApp.animal', verbose_name='Animal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamentoconsultas',
            name='data_consulta',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data da Consulta'),
        ),
        migrations.AddField(
            model_name='agendamentoconsultas',
            name='tutor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='MariaAlvezApp.tutor', verbose_name='Tutor'),
            preserve_default=False,
        ),
    ]
