# Generated by Django 5.2.3 on 2025-07-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0009_estoquemedicamento_tipo_medicamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoquemedicamento',
            name='medicamento',
            field=models.CharField(max_length=255, unique=True, verbose_name='Medicamento'),
        ),
    ]
