# Generated by Django 5.2.3 on 2025-06-15 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0005_remove_registrovermifugos_data_readiministracao_and_more'),
        ('MariaAlvezApp', '0010_agendamentoconsultas_animal_and_more'),
    ]

    operations = [
    ]
