# Generated by Django 5.2.3 on 2025-07-02 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0006_painelgerencial'),
        ('MariaAlvezApp', '0010_alter_estoquemedicamento_medicamento'),
    ]

    operations = [
    ]
