# Generated by Django 5.2.3 on 2025-07-02 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0011_merge_20250702_1951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PainelGerencial',
        ),
    ]
