# Generated by Django 5.2.3 on 2025-06-15 19:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0011_merge_20250615_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoEstoqueMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=255, verbose_name='Medicamento')),
                ('lote', models.CharField(max_length=100, verbose_name='Código do Lote')),
                ('data_validade', models.DateField(verbose_name='Data de Validade')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10, verbose_name='Tipo de Movimento')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade Movimentada')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data do Movimento')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Movimento de Estoque',
                'verbose_name_plural': 'Movimentos de Estoque',
            },
        ),
        migrations.CreateModel(
            name='EstoqueMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=255, verbose_name='Medicamento')),
                ('lote', models.CharField(max_length=100, verbose_name='Lote')),
                ('data_validade', models.DateField(verbose_name='Data de Validade')),
                ('quantidade', models.PositiveIntegerField(default=0, editable=False, verbose_name='Quantidade em Estoque')),
                ('data_cadastro', models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Data de Entrada')),
            ],
            options={
                'verbose_name': 'Lote de Medicamento',
                'verbose_name_plural': 'Estoque de Medicamentos',
                'unique_together': {('lote',)},
            },
        ),
    ]
