# Generated by Django 5.2.3 on 2025-07-03 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0012_delete_painelgerencial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultaclinica',
            name='agendamento_origem',
            field=models.OneToOneField(blank=True, help_text='Agendamento que originou esta consulta (se houver).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consulta_gerada', to='MariaAlvezApp.agendamentoconsultas', verbose_name='Agendamento de Origem'),
        ),
    ]
