# Generated by Django 5.2.3 on 2025-06-15 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0012_movimentoestoquemedicamento_estoquemedicamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrovacinacao',
            name='medicamento',
        ),
        migrations.AddField(
            model_name='registrovacinacao',
            name='medicamento_aplicado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MariaAlvezApp.estoquemedicamento', verbose_name='Medicamento/Lote Aplicado'),
        ),
        migrations.AlterField(
            model_name='registrovacinacao',
            name='data_aplicacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Aplicação'),
        ),
    ]
