# Generated by Django 5.2.3 on 2025-06-15 20:17

import MariaAlvezApp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0013_remove_registrovacinacao_medicamento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicamentos',
            options={'verbose_name': 'Medicamento (Genérico)', 'verbose_name_plural': 'Medicamentos (Genéricos)'},
        ),
        migrations.AlterUniqueTogether(
            name='estoquemedicamento',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='registrovermifugos',
            name='medicamento',
        ),
        migrations.AddField(
            model_name='exames',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MariaAlvezApp.animal', verbose_name='Animal'),
        ),
        migrations.AddField(
            model_name='exames',
            name='data_exame',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Exame'),
        ),
        migrations.AddField(
            model_name='exames',
            name='resultado',
            field=models.TextField(blank=True, null=True, verbose_name='Resultado'),
        ),
        migrations.AddField(
            model_name='exames',
            name='tipo_exame',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Exame'),
        ),
        migrations.AddField(
            model_name='medicamentos',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='medicamentos',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Medicamento'),
        ),
        migrations.AddField(
            model_name='registrovermifugos',
            name='medicamento_administrado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MariaAlvezApp.estoquemedicamento', verbose_name='Vermífugo/Lote Administrado'),
        ),
        migrations.AddField(
            model_name='veterinario',
            name='crmv',
            field=models.CharField(default='00000-UF', max_length=50, unique=True, verbose_name='CRMV'),
        ),
        migrations.AddField(
            model_name='veterinario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='veterinario',
            name='nome',
            field=models.CharField(default='Nome do Veterinário', max_length=255, verbose_name='Nome do Veterinário'),
        ),
        migrations.AddField(
            model_name='veterinario',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='castrado',
            field=models.BooleanField(default=False, verbose_name='Castrado(a)'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.CharField(default='Especie', max_length=100, verbose_name='Espécie'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='idade_anos',
            field=models.PositiveIntegerField(default=0, verbose_name='Anos'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='idade_dias',
            field=models.PositiveIntegerField(default=0, verbose_name='Dias'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='idade_meses',
            field=models.PositiveIntegerField(default=0, verbose_name='Meses'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='nome',
            field=models.CharField(default='Nome', max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='peso',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Peso em quilogramas', max_digits=10, verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='rfid',
            field=models.CharField(default='0', max_length=128, unique=True, verbose_name='RFID'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], default='Sexo', max_length=15, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='estoquemedicamento',
            name='lote',
            field=models.CharField(max_length=100, unique=True, verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='registrovacinacao',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MariaAlvezApp.animal', verbose_name='Animal'),
        ),
        migrations.AlterField(
            model_name='registrovermifugos',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MariaAlvezApp.animal', verbose_name='Animal'),
        ),
        migrations.AlterField(
            model_name='registrovermifugos',
            name='data_administracao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Administração'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='cep',
            field=models.CharField(max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='cidade',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[MariaAlvezApp.models.validar_cpf], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='endereco',
            field=models.CharField(max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='estado',
            field=models.CharField(max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='telefone',
            field=models.CharField(max_length=15, validators=[MariaAlvezApp.models.validar_telefone], verbose_name='Telefone'),
        ),
        migrations.AddIndex(
            model_name='agendamentoconsultas',
            index=models.Index(fields=['data_consulta'], name='MariaAlvezA_data_co_02161e_idx'),
        ),
    ]
