# Generated by Django 5.2.3 on 2025-07-03 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0013_consultaclinica_agendamento_origem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamentoconsultas',
            name='tutor',
        ),
    ]
