# Generated by Django 5.2.4 on 2025-07-03 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0014_remove_agendamentoconsultas_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrovacinacao',
            name='medicamento_aplicado',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_medicamento': 'vacina'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MariaAlvezApp.estoquemedicamento', verbose_name='Medicamento/Lote Aplicado'),
        ),
        migrations.AlterField(
            model_name='registrovermifugos',
            name='medicamento_administrado',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_medicamento': 'vermifugo'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MariaAlvezApp.estoquemedicamento', verbose_name='Vermífugo/Lote Administrado'),
        ),
    ]
