# Generated by Django 5.2.3 on 2025-07-03 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0014_remove_agendamentoconsultas_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='tutor',
            field=models.ForeignKey(help_text='Selecione o tutor responsável por este animal.', on_delete=django.db.models.deletion.CASCADE, related_name='animais_tutor', to='MariaAlvezApp.tutor', verbose_name='Tutor do Animal'),
        ),
    ]
