# Generated by Django 5.2.3 on 2025-06-15 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0014_alter_medicamentos_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medicamentos',
        ),
    ]
