# Generated by Django 5.2 on 2025-06-15 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0011_merge_20250615_1734'),
        ('MariaAlvezApp', '0014_alter_medicamentos_options_and_more'),
    ]

    operations = [
    ]
