# Generated by Django 5.2.4 on 2025-07-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0015_alter_registrovacinacao_medicamento_aplicado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exames',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Exame'),
        ),
        migrations.AlterField(
            model_name='exames',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Imagem', 'Imagem'), ('Laboratorial', 'Laboratorial'), ('Clínico', 'Clínico')], max_length=50, null=True, verbose_name='Tipo de Exame'),
        ),
    ]
