# Generated by Django 5.2.3 on 2025-06-15 22:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0015_delete_medicamentos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exames',
            options={'ordering': ['animal__nome', '-data_exame'], 'verbose_name': 'Exame', 'verbose_name_plural': 'Exames'},
        ),
        migrations.RemoveField(
            model_name='exames',
            name='id',
        ),
        migrations.RemoveField(
            model_name='exames',
            name='resultado',
        ),
        migrations.RemoveField(
            model_name='exames',
            name='tipo_exame',
        ),
        migrations.AddField(
            model_name='exames',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='exames/', verbose_name='Anexo do Exame'),
        ),
        migrations.AddField(
            model_name='exames',
            name='descricao',
            field=models.TextField(default='', verbose_name='Descrição do Exame'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exames',
            name='id_exame',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='exames',
            name='nome',
            field=models.CharField(default='', max_length=100, verbose_name='Nome do Exame'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exames',
            name='tipo',
            field=models.CharField(choices=[('Imagem', 'Imagem'), ('Laboratorial', 'Laboratorial'), ('Clínico', 'Clínico')], default='', max_length=50, verbose_name='Tipo de Exame'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exames',
            name='animal',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='MariaAlvezApp.animal', verbose_name='Animal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exames',
            name='data_exame',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Realização do Exame'),
        ),
    ]
