# Generated by Django 5.2.3 on 2025-06-15 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0015_merge_20250615_1736'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medicamentos',
        ),
    ]
