# Generated by Django 5.2.3 on 2025-06-15 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0011_merge_20250615_1734'),
        ('MariaAlvezApp', '0016_alter_exames_options_remove_exames_id_and_more'),
    ]

    operations = [
    ]
