# Generated by Django 5.2.3 on 2025-07-03 02:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MariaAlvezApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaTerceirizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('cnpj', models.CharField(help_text='Formato: XX.XXX.XXX/XXXX-XX', max_length=18, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Empresa Terceirizada',
                'verbose_name_plural': 'Empresas Terceirizadas',
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='RegistroServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_procedimento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora do Procedimento')),
                ('valor_servico', models.DecimalField(blank=True, decimal_places=2, help_text='Custo do serviço. Deixe em branco se não aplicável.', max_digits=10, null=True, verbose_name='Valor do Serviço (R$)')),
                ('medicamentos_aplicados', models.TextField(blank=True, help_text='Liste os medicamentos e dosagens.', verbose_name='Medicamentos Aplicados')),
                ('outros_procedimentos', models.TextField(blank=True, help_text='Descreva outros procedimentos, como curativos, exames, etc.', verbose_name='Outros Procedimentos Realizados')),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MariaAlvezApp.animal', verbose_name='Animal Atendido')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Terceiros.empresaterceirizada', verbose_name='Empresa Prestadora')),
            ],
            options={
                'verbose_name': 'Registro de Serviço',
                'verbose_name_plural': 'Registros de Serviços',
                'ordering': ['-data_hora_procedimento'],
            },
        ),
    ]
