# Generated by Django 5.2.3 on 2025-06-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TesteTerceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_teste', models.CharField(max_length=50, verbose_name='Nome Teste')),
            ],
            options={
                'verbose_name': 'Teste',
                'verbose_name_plural': 'Teste',
            },
        ),
    ]
