# Generated by Django 5.2.4 on 2025-07-03 22:42

import Terceiros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Terceiros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresaterceirizada',
            name='cnpj',
            field=models.CharField(help_text='Número de Cadastro Nacional de Pessoa Jurídica (14 dígitos).', max_length=18, unique=True, validators=[Terceiros.models.validar_cnpj], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='empresaterceirizada',
            name='email',
            field=models.EmailField(blank=True, help_text='Endereço de e-mail da empresa.', max_length=254, null=True, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='empresaterceirizada',
            name='razao_social',
            field=models.CharField(help_text='Nome completo da empresa.', max_length=200, unique=True, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='empresaterceirizada',
            name='telefone',
            field=models.CharField(blank=True, help_text='Telefone do tutor com DDD. Ex: 49998086201 (apenas números, a máscara será aplicada automaticamente).', max_length=15, null=True, validators=[Terceiros.models.validar_telefone], verbose_name='Telefone'),
        ),
    ]
