# Generated by Django 5.2.4 on 2025-07-04 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaAlvezApp', '0007_alter_registrovermifugos_animal_and_more'),
        ('Terceiros', '0002_alter_empresaterceirizada_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroservico',
            name='animal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MariaAlvezApp.animal', verbose_name='Animal Atendido'),
        ),
    ]
